========================================
            ERROR EN EL PROGRAMA
========================================
Hora del error: Fri Aug 15 00:06:26 2025
Tipo de error: error
Mensaje: font not initialized

--- Traceback ---
Traceback (most recent call last):
  File "C:\Users\Wilson\.vscode\ai\run_game.py", line 708, in <module>
    start_diablo_mode(ia_players)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Wilson\.vscode\ai\run_game.py", line 643, in start_diablo_mode
    winner, _, _ = start_game(player1, player2, player1_name, player2_name,
                   ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              time_limit=current_time_limit, consecutive_score_limit=1, point_score_limit=1,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              diablo_mode=True, diablo_round=round_num, diablo_points=diablo_points, diablo_victories=diablo_victories,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              ball_speed=current_ball_speed)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Wilson\.vscode\ai\run_game.py", line 139, in start_game
    font = pygame.font.Font(None, 74)
pygame.error: font not initialized
